#!/usr/bin/env ruby

require 'socket'
require 'pathname'

puts "👋 Welcome to Ruby in Hollywood Battlesnake!

Bundling to make sure you've got the gems we're using...
"

output = `bundle install --gemfile Gemfile`

if $?.exitstatus != 0
  puts output
  exit 1
end

puts "Bundle complete, registering you with our Battlesnake server..."

$game_id_file = Pathname.new(__FILE__).dirname.dirname.join('.gameid')

def create_game
  puts
  puts "To create your first game (you will hopefully create many with `script/battle-with`),"
  puts "what's a good name for your snake?"
  me = gets.chomp
  puts "What's a good name for your snake's nemesis?"
  nemesis = gets.chomp
  ip_address = Socket.ip_address_list.find { |ai| ai.ipv4? && !ai.ipv4_loopback? }.ip_address

  game_id = `./script/battle-with "#{me}=http://#{ip_address}:9292" "#{nemesis}=http://#{ip_address}:9292"`
  File.write($game_id_file, game_id)

  game_id
end

game_id = if $game_id_file.exist?
  id = $game_id_file.read
  # sometimes the .gameid file is created but empty since it failed previously,
  # make sure we try again if we don't get one read.
  unless id && id.length > 0
    id = create_game
  end
  id
else
  create_game
end

puts "
Awesome! You should be setup!

From here you can run `script/snake` to start your 🐍

and then visit #{ENV["SNAKE_SERVER"] || "http://battlesnake.local:3000"}/#{game_id} to watch your snake duke it out!
"

